"""2. Add 'slug' field to User

Revision ID: 7a3684199378
Revises: efd148533c0e
Create Date: 2023-05-23 14:07:32.928687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3684199378'
down_revision = 'efd148533c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###
