"""3. File handler

Revision ID: 7cbb186d288c
Revises: 7a3684199378
Create Date: 2023-05-24 13:35:22.922173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbb186d288c'
down_revision = '7a3684199378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
